language: node_js
node_js: 12

cache:
  yarn: true

jobs:
  include:
    - stage: test
      script:
        - yarn
        - yarn lint
        - yarn build
    - stage: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn semantic-release
